In [1]:
import torch

In [3]:
# 创建一个行向量x，包含0-12整数
x=torch.arange(12)
# 通过张量的shape访问张量形状
print(x.shape,x.numel())


torch.Size([12]) 12


In [4]:
# 改变张量形状为3行四列矩阵，张量大小不变
X=x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [6]:
# 对行列指定-1自动计算维度
X1=x.reshape(-1,4)
X2=x.reshape(6,-1)
print(X1)
print(X2)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


In [8]:
# 使用全0、全1、其他常量初始化张量
t1=torch.zeros((2,4,4))
print(t1)
t2=torch.ones((2,4,4))
print(t2)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [9]:
# 有时我们想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值。 例如，当我们构造数组来作为神经网络中的参数时，
# 我们通常会随机初始化参数的值。 以下代码创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布
# （正态分布）中随机采样。
t3=torch.randn(3, 4)
print(t3)

tensor([[-0.6425,  1.8955,  0.8870, -1.0169],
        [-0.4333,  1.7830,  0.9683, -0.4386],
        [-1.8300, -0.7870,  0.2090,  2.7326]])


In [11]:
# 我们还可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。 
# 在这里，最外层的列表对应于轴0，内层的列表对应于轴1。
torch.tensor([[2,1,3,4],[1,2,3,4],[5,6,7,8]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])